main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views


account = ([
    path('profile/', views.profile, name="profile"),
    path('user/', views.search_user, name="search"),
    path('user/<str:username>', views.get_user, name="get"),
], "accounts"
)

mod = (
    [
        path('', views.mod_home, name="homepage"),
        path('ticket/<int:ticket>', views.mod_home, name="ticket"),
        path('no_auth', views.no_auth, name="no_auth"),
        path('user/<int:user>', views.user_tickets, name="user"),
        path('comment/<int:comment_id>', views.mod_comment, name="comment"),
        path('report/<int:comment_id>', views.report, name="report"),
        path('block/<int:comment_id>', views.block, name="block"),
    ], "moderation"
)



#app_name = "main"
urlpatterns = [
    path('admin/', admin.site.urls),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("accounts/", include(account)),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", views.index, name="homepage"),
    path('ponudbe/', include("ponudbe.urls")),
    path('moderation/', include(mod)),
    path('comment/<int:parent>', views.comment, name="comment"),
]

ponudbe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

transactions = ([
    path("buy/<int:ponudba>", views.buy, name="buy"),
    path("confirm/<int:ponudba>", views.confirm, name="confirm"),
    path("recieved/<int:ponudba>", views.recieved, name="recieved"),
    path("finish/<int:ponudba>", views.finish, name="finish"),
    path("cancel/<int:ponudba>", views.cancel, name="cancel"),
    path("suggest/<int:ponudba>", views.suggest, name="suggest"),
], "transactions")

app_name = "ponudbe"
urlpatterns = [
    path("", views.index, name="index"),
    path("get/<int:ponudba_id>", views.get, name="get"),
    path("my", views.moje, name="moje"),
    path("new", views.create, name="new"),
    path("delete/<int:ponudba>", views.delete, name="delete"),
    path("edit/<int:ponudba>", views.edit, name="edit"),
    path("card-autocomplete/", views.KartaAutocomplete.as_view(), name="card_autocomplete"),
    path("transactions/", include(transactions)),
]

treasure_chest/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', include("main.urls")),
    
]
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

ponudbe/models.py
from django.db import models
from django.conf import settings
from django.db.models import CharField, Model, IntegerField, ManyToManyField, FloatField, ForeignKey, DateField, BooleanField

# Create your models here.

from main.models import Komentar, Uporabnik


class Set(Model):
    OP = "OP", "One Piece"
    EB = "EB", "Extra Booster"
    PR = "PR", "Promotional"
    tips = [OP, EB, PR]

    ime = CharField(max_length=50)
    zapored = IntegerField()
    tip = CharField(max_length=2, choices=tips)

    def code(self):
        return f"{self.tip}{self.zapored:02}"
    

    def __str__(self):
        code = self.code()
        return f"{code}: {self.ime}"
    
    

class Barva(Model):
    barva = CharField(max_length=6)
    short = CharField(max_length=2)

    def __str__(self):
        return self.barva
    
class Skupina(Model):
    ime = CharField(max_length=50)

    def __str__(self):
        return f"{self.ime}"


class Karta(Model):

    RARITY_CHOICES = [
        (
            "normal",
            (
                ("C", "Common"),
                ("UC", "Uncommon"),
                ("R", "Rare"),
                ("SR", "Super Rare"),
                ("SEC", "Secret"),
            ),
        ),
        (
            "alternate",
            (
                ("Rp", "Rare+"),
                ("SRp", "Super Rare+"),
                ("SEA", "Secret+"),
                ("M", "Manga")
            )
        )
    ]
    VRSTA_CHOICES = [
        ("L", "Leader"),
        ("C", "Character"),
        ("S", "Stage"),
        ("E", "Event"),
    ]
    TOCKE = [
        ("N", "None"),
        ("1", 1),
        ("2", 2),
        ("3", 3),
        ("4", 4),
        ("5", 5),
        ("6", 6),
    ]
    NAPADI = [
        ("SLH", "Slash"),
        ("STR", "Strength"),
        ("SPC", "Special"),
        ("WIS", "Wisdom"),
        ("RNG", "Ranged"),
    ]

    zaporedna = IntegerField()
    ime = CharField(max_length=50)
    barva = ManyToManyField(Barva)
    opis = CharField(max_length=255)
    redkost = CharField(max_length=3, choices=RARITY_CHOICES)
    vrsta = CharField(max_length=1, choices=VRSTA_CHOICES)
    tocke = CharField(max_length=1, choices= TOCKE, null= True, blank= True)
    napad = CharField(max_length=3, choices=NAPADI, null= True, blank= True)
    skoda = IntegerField(null= True, blank= True)
    stevec = IntegerField(null= True, blank= True)
    strosek = IntegerField(null= True, blank= True)
    verzija = IntegerField()
    vrednost = FloatField()
    skupine = ManyToManyField(Skupina)
    set_id = ForeignKey(Set, on_delete=models.CASCADE)


    def is_alt(self):
        return self.redkost in self.rarity_choices[1]
    
    def __str__(self) -> str:
        code = self.set_id.code()
        return f"{self.ime} ({code}-{self.zaporedna:03}) (V.{self.verzija})"


class Ponudba(Model):
    STANJA = [
        ("N", "Na voljo"),
        ("T", "v Transakciji"),
        ("G", "V ponudbi"),
        ("V", "v Prevzemu"),
        ("Z", "Zaključeno"),
        ("P", "Preklicano"),
    ]
    TIPI = [
        ("K", "Kupim"),
        ("P", "Prodam")
    ]
    stanje = CharField(max_length=1, choices=STANJA, default=STANJA[0][0])
    datum = DateField(auto_now_add=True)
    tip = CharField(max_length=1, choices=TIPI)
    cena = FloatField()
    dodatno = CharField(max_length=255)
    karta = ForeignKey(Karta, on_delete=models.CASCADE)
    ustvaril = ForeignKey(Uporabnik, on_delete=models.CASCADE, related_name="ust")
    zakljucil = ForeignKey(Uporabnik, on_delete=models.CASCADE, null= True, blank= True, related_name="zak")
    mnenje = ForeignKey(Komentar, on_delete=models.CASCADE, null=True, blank=True)

ponudbe/forms.py
from django import forms
from .models import Ponudba, Karta
from dal import autocomplete


class EditPonudbaForm(forms.Form):
    cena = forms.FloatField()
    dodatno = forms.CharField(max_length=200, required=False)

class PonudbaForm(forms.Form):
    tip = forms.ChoiceField(choices= Ponudba.TIPI)
    cena = forms.FloatField()
    dodatno = forms.CharField(max_length=200, required=False)
    karta = forms.ModelChoiceField(queryset=Karta.objects.all(),widget=autocomplete.ModelSelect2(url='ponudbe:card_autocomplete'))


class MnenjeForm(forms.Form):
    mnenje = forms.CharField(required=False, widget=forms.Textarea(
        attrs={
            "rows": 4,
            "class": "h-100 w-100"
        }
    ) )

ponudbe/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.db.models import Q

from main.forms import ReportForm
from main.models import Komentar
from .forms import EditPonudbaForm, MnenjeForm, PonudbaForm
from django.contrib.auth.decorators import login_required

from dal import autocomplete
from .models import Ponudba, Karta
from .filters import PonudbaFilter

# Create your views here.

class KartaAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        cards = Karta.objects.all()
        if self.q:
            cards = cards.filter(ime__istartswith=self.q) | cards.filter(set_id__tip__istartswith=self.q)
        return cards
    

def index(req):
    ctx = {}
    ponudbe = Ponudba.objects.filter(stanje="N")
    ctx["filter"] = PonudbaFilter(req.GET, queryset=ponudbe)
    print(ctx)
    return render(req, 'ponudbe/ponudbe.html', context=ctx)

def get(req, ponudba_id):
    ctx = {}
    ctx["ponudba"] = get_object_or_404(Ponudba, id=ponudba_id)
    ctx["edit_form"] = EditPonudbaForm(initial={
        "cena": ctx["ponudba"].cena,
        "dodatno": ctx["ponudba"].dodatno,
    })
    ctx["reply_form"] = MnenjeForm()
    ctx["report_form"] = ReportForm()
    return render(req, 'ponudbe/ponudba_page.html', context=ctx)


@login_required(login_url='/accounts/login/')
def create(req):
    ctx = {}
    ctx["cards"] = Karta.objects.all()
    if req.method == "POST":
        form = PonudbaForm(req.POST)
        if form.is_valid():
            data = form.cleaned_data
            Ponudba.objects.create(
                tip=data["tip"],
                cena=data["cena"],
                dodatno=data["dodatno"],
                karta=data["karta"],
                ustvaril=req.user.uporabnik
                )
            return redirect("ponudbe:moje")
    else:
        form = PonudbaForm()

    ctx["form"] = form
    return render(req, "ponudbe/new_ponudba.html", context=ctx)

@login_required(login_url='/accounts/login/')
def moje(req):
    ctx = {}
    m_ponudbe = Ponudba.objects.filter(ustvaril=req.user.uporabnik)
    d_ponudbe = Ponudba.objects.filter(zakljucil=req.user.uporabnik)
    ctx["na_voljo"] = m_ponudbe.filter(stanje="N")
    ctx["trans"] = m_ponudbe.filter(stanje="T")
    ctx["prevz"] = d_ponudbe.filter(stanje="V")
    ctx["oddaj"] = m_ponudbe.filter(stanje="V")

    ctx["nakup"] = d_ponudbe.filter(stanje="G")
    
    #zakljuceno
    ctx["moji_zaklj"] = m_ponudbe.filter(stanje="Z")
    ctx["drugi_zaklj"] = d_ponudbe.filter(stanje="Z")
    #preklicano
    ctx["moji"] = m_ponudbe.filter(stanje="P")
    ctx["drugi"] = d_ponudbe.filter(stanje="P")

    return render(req, "ponudbe/moje_ponudbe.html", context=ctx)

@login_required(login_url='/accounts/login/')
def delete(req, ponudba):
    ponudba = get_object_or_404(Ponudba, id=ponudba)
    print("delete")
    return redirect("ponudbe:moje")

@login_required(login_url='/accounts/login/')
def edit(req, ponudba):
    ponudba = get_object_or_404(Ponudba, id=ponudba)
    if req.method == "POST":
        form = EditPonudbaForm(req.POST)
        if form.is_valid():
            data = form.cleaned_data
            print(f"valid: {data}")
            ponudba.dodatno = data["dodatno"]
            ponudba.cena = data["cena"]
            ponudba.save()
    return HttpResponseRedirect(req.META.get('HTTP_REFERER'))

@login_required(login_url='/accounts/login/')
def buy(req, ponudba):
    ponudba = get_object_or_404(Ponudba, id=ponudba)
    if ponudba.stanje == "N" and req.user.uporabnik != ponudba.ustvaril:
        ponudba.stanje = "T"
        ponudba.zakljucil = req.user.uporabnik
        ponudba.save()
    return HttpResponseRedirect(req.META.get('HTTP_REFERER'))

@login_required(login_url='/accounts/login/')
def confirm(req, ponudba):
    ponudba = get_object_or_404(Ponudba, id=ponudba)
    if ponudba.stanje in ["T","G"]:
        ponudba.stanje = "V"
        ponudba.save()
    return HttpResponseRedirect(req.META.get('HTTP_REFERER'))

@login_required(login_url='/accounts/login/')
def recieved(req, ponudba):
    ponudba = get_object_or_404(Ponudba, id=ponudba)
    if ponudba.stanje == "V":
        ponudba.stanje = "Z"
        ponudba.save()
    return HttpResponseRedirect(req.META.get('HTTP_REFERER'))


@login_required(login_url='/accounts/login/')
def cancel(req, ponudba):
    ponudba = get_object_or_404(Ponudba, id=ponudba)
    prev = ponudba.stanje
    ponudba.stanje = "C"
    if req.method == "POST":
        form = MnenjeForm(req.POST)
        if form.is_valid():
            data = form.cleaned_data
            comment = Komentar.objects.create(
                user=req.user.uporabnik,
                content=data["mnenje"],
            )
            ponudba.mnenje = comment
    if prev == "G":
        comm = Komentar.objects.get(content=f"moved to <{ponudba.id}>")
        old = Ponudba.objects.get(mnenje=comm)
        old.stanje = "N"
        old.mnenje = None
        old.save()
    ponudba.save()
    return HttpResponseRedirect(req.META.get('HTTP_REFERER'))

@login_required(login_url='/accounts/login/')
def finish(req, ponudba):
    ponudba = get_object_or_404(Ponudba, id=ponudba)
    ponudba.stanje = "Z"
    if req.method == "POST":
        form = MnenjeForm(req.POST)
        if form.is_valid():
            data = form.cleaned_data
            comment = Komentar.objects.create(
                user=req.user.uporabnik,
                content=data["mnenje"],
            )
            ponudba.mnenje = comment
    ponudba.save()
    return HttpResponseRedirect(req.META.get('HTTP_REFERER'))


@login_required(login_url='/accounts/login/')
def suggest(req, ponudba):
    ponudba = get_object_or_404(Ponudba, id=ponudba)
    ponudba.stanje = "G"
    new = Ponudba.objects.create(
        stanje = "G",
        tip = "P",
        ustvaril = req.user.uporabnik,
        zakljucil = ponudba.ustvaril,
        dodatno = ponudba.dodatno,
        cena = ponudba.cena,
        karta = ponudba.karta,
    )
    kom = Komentar.objects.create(
        user=req.user.uporabnik,
        content=f"moved to <{new.id}>"
    )
    ponudba.mnenje = kom
    ponudba.save()
    return HttpResponseRedirect(req.META.get('HTTP_REFERER'))

templates/ponudbe/moje_ponudbe.html
{% extends "index.html" %}

{% block title %}
Moje Ponudbe
{% endblock title %}


{% block content %}
<section class="container content border rounded">
    <a class="btn btn-success" href="{% url "ponudbe:new" %}">New Ponudba</a>
    <div class="row p-3">
        <h2 class=" border-bottom" data-bs-toggle="collapse" href="#oddaj" role="button" aria-expanded="false" aria-controls="oddaj">
            Oddaj karte
        </h2>
        <div class="collapse show" id="oddaj">
            {% for ponudba in oddaj %}
            <a href="{% url "ponudbe:get"  ponudba.id%}" style="text-decoration:none">
                {% include "ponudbe/ponudba.html"  with ponudba=ponudba%}
    
            </a>
            {% endfor %}
        </div>
        <h2 class="border-bottom">Potrdi</h2>
        <div class="col p-3 rounded border">
            <h2 class="border-bottom" data-bs-toggle="collapse" href="#prejem" role="button" aria-expanded="false" aria-controls="prejem">
                Prejem
            </h2>
            <div class="collapse show" id="prejem">
                {% for ponudba in prevz %}
                <a href="{% url "ponudbe:get"  ponudba.id%}" style="text-decoration:none">
                    {% include "ponudbe/ponudba.html"  with ponudba=ponudba%}
                </a>
                {% endfor %}
            </div>
        </div>
        <div class="col p-3 rounded border">
            <h2 class="border-bottom" data-bs-toggle="collapse" href="#kupca" role="button" aria-expanded="false" aria-controls="kupca">
                Kupca
            </h2>
            <div class="collapse show" id="kupca">
                {% for ponudba in trans %}
                <a href="{% url "ponudbe:get"  ponudba.id%}" style="text-decoration:none">
                    {% include "ponudbe/ponudba.html"  with ponudba=ponudba%}
                </a>
                {% endfor %}
            </div>
        </div>
        <div class="col p-3 rounded border">
            <h2 class="border-bottom" data-bs-toggle="collapse" href="#nakup" role="button" aria-expanded="false" aria-controls="nakup">
                Nakup
            </h2>
            <div class="collapse show" id="nakup">
                {% for ponudba in nakup %}
                <a href="{% url "ponudbe:get"  ponudba.id%}" style="text-decoration:none">
                    {% include "ponudbe/ponudba.html"  with ponudba=ponudba%}
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
    <h2 class=" border-bottom" data-bs-toggle="collapse" href="#na_voljo" role="button" aria-expanded="false" aria-controls="na_voljo">
        Na voljo
    </h2>
    <div class="collapse show" id="na_voljo">
        {% for ponudba in na_voljo %}
        <a href="{% url "ponudbe:get"  ponudba.id%}" style="text-decoration:none">
            {% include "ponudbe/ponudba.html"  with ponudba=ponudba%}

        </a>
        {% endfor %}
    </div>
    <h2 class="border-bottom" data-bs-toggle="collapse" href="#preklicano" role="button" aria-expanded="false" aria-controls="preklicano">
        Preklicano
    </h2>
    <div class="collapse show row" id="preklicano">
        <div class="col p-3 rounded border">
            <h2 class="border-bottom" data-bs-toggle="collapse" href="#moji" role="button" aria-expanded="false" aria-controls="moji">
                Moji
            </h2>
            <div class="collapse show" id="moji">
                {% for ponudba in moji %}
                <a href="{% url "ponudbe:get"  ponudba.id%}" style="text-decoration:none">
                    {% include "ponudbe/ponudba.html"  with ponudba=ponudba%}
                </a>
                {% endfor %}
            </div>
        </div>
        <div class="col p-3 rounded border">
            <h2 class="border-bottom" data-bs-toggle="collapse" href="#drugi" role="button" aria-expanded="false" aria-controls="drugi">
                Drugi
            </h2>
            <div class="collapse show" id="drugi">
                {% for ponudba in drugi %}
                <a href="{% url "ponudbe:get"  ponudba.id%}" style="text-decoration:none">
                    {% include "ponudbe/ponudba.html"  with ponudba=ponudba%}
                </a>
                {% endfor %}
            </div>
        </div>
        <h2 class=" border-bottom" data-bs-toggle="collapse" href="#zakljuceno" role="button" aria-expanded="false" aria-controls="zakljuceno">
            zaključeno
        </h2>
        <div class="collapse show row" id="preklicano">
            <div class="col p-3 rounded border">
                <h2 class="border-bottom" data-bs-toggle="collapse" href="#moji_zaklj" role="button" aria-expanded="false" aria-controls="moji_zaklj">
                    Moji
                </h2>
                <div class="collapse show" id="moji_zaklj">
                    {% for ponudba in moji_zaklj %}
                    <a href="{% url "ponudbe:get"  ponudba.id%}" style="text-decoration:none">
                        {% include "ponudbe/ponudba.html"  with ponudba=ponudba%}
                    </a>
                    {% endfor %}
                </div>
            </div>
            <div class="col p-3 rounded border">
                <h2 class="border-bottom" data-bs-toggle="collapse" href="#drugi_zaklj" role="button" aria-expanded="false" aria-controls="drugi_zaklj">
                    Drugi
                </h2>
                <div class="collapse show" id="drugi_zaklj">
                    {% for ponudba in drugi_zaklj %}
                    <a href="{% url "ponudbe:get"  ponudba.id%}" style="text-decoration:none">
                        {% include "ponudbe/ponudba.html"  with ponudba=ponudba%}
                    </a>
                    {% endfor %}
                </div>
            </div>
    </div>
{% endblock content %}

templates/ponudbe/new_ponudba.html
{% extends "index.html" %}


{% block title %}
New Ponudba
{% endblock title %}


{% block content %}

<form method="post">
    {% csrf_token %}
    {{form.as_div}}
    <button type="submit">New ponudba</button>
</form>
{{form.media}}
{% endblock content %}

templates/ponudbe/ponudba.html
<div class="rounded border p-2 row">
    <div class="col text-{% if ponudba.tip == "K" %}warning{% else %}success{%endif%}">
        {{ponudba.get_tip_display}}
    </div>
    <div class="col">
        <a href="{% url "accounts:get"  ponudba.ustvaril.user.username %}">
            {{ponudba.ustvaril}}
        </a>
        {% if ponudba.zakljucil %}
            ->
            <a href="{% url "accounts:get"  ponudba.zakljucil.user.username %}">
                {{ponudba.zakljucil}}
            </a>
        {% endif %}
    </div>
    <div class="col">
        {{ponudba.karta}}
    </div>
    <div class="col">
        {{ponudba.cena}} €
    </div>
    <div class="col">
        {{ponudba.dodatno}}
    </div>
    {% if stanje %}
        <div class="col">
            {{ponudba.get_stanje_display}}
        </div>
    {% endif %}
    {% if ponudba.stanje == "Z" %}
    <div class="col">
        {% if ponudba.mnenje %}
            {% include "komentar/review.html" with komentar=ponudba.mnenje %}
        {% endif %}
    </div>
    {% endif %}
</div>

templates/ponudbe/ponudba_page.html
{% extends "index.html" %}

{% block title %}
Ponudba: {{ponudba.id}}
{% endblock title %}


{% block content %}

<h1>Ponudba: {{ponudba.id}}</h1>
{% include "ponudbe/ponudba.html" with ponudba=ponudba  stanje=True%}

{% if user.uporabnik == ponudba.ustvaril %}
    {% if ponudba.stanje == "N" %}
        <div class="collapse" id="edit">
            <form class="section border rounded" method="post" action="{% url "ponudbe:edit" ponudba.id%}">
                <div class="row">
                    {% csrf_token %}
                    {{edit_form}}
                    <button  class="btn btn-success" type="submit">Save</button>
                </div>
            </form>
        </div>
        <div>
            <button class="btn btn-warning col-auto" data-bs-toggle="collapse" href="#edit" role="button" aria-expanded="false" aria-controls="edit">Uredi</button>  
            <a href="{% url "ponudbe:delete" ponudba.id %}" class="btn btn-danger col-auto">Delete</a>  
        </div>
    {% endif %}
    {% if ponudba.stanje == "T" %}
        <div>
            <p>User <a href="{% url "accounts:get" ponudba.zakljucil %}"><code>{{ponudba.zakljucil}}</code></a> wants to create a transaction with you.</p>
            <form method="post" >
                {% csrf_token %}
                {{reply_form}}
                <button class="btn btn-success" type="submit" formaction="{% url "ponudbe:transactions:confirm" ponudba.id %}">Confirm</button>
                <button class="btn btn-danger" type="submit" formaction="{% url "ponudbe:transactions:cancel" ponudba.id %}">Cancel</button>
            </form>

        </div>
    {% endif %}
{% endif %}
{% if user.uporabnik %}
    {% if ponudba.stanje == "N" and user.uporabnik != ponudba.ustvaril%}
        {% if ponudba.tip == "P"%}
            <a href="{% url "ponudbe:transactions:buy" ponudba.id %}" class="btn btn-success">Buy</a>
        {% endif %}
        {% if ponudba.tip == "K" %}
        <a href="{% url "ponudbe:transactions:suggest" ponudba.id %}" class="btn btn-success">Offer</a>
        {% endif %}
    {% endif %}
    {% if user.uporabnik == ponudba.zakljucil and ponudba.stanje == "G"%}
    <form method="post" >
        {% csrf_token %}
        {{reply_form}}
        <button class="btn btn-success" type="submit" formaction="{% url "ponudbe:transactions:confirm" ponudba.id %}">Confirm</button>
        <button class="btn btn-danger" type="submit" formaction="{% url "ponudbe:transactions:cancel" ponudba.id %}">Cancel</button>
        (you can accept that you will buy the card or cancel)
    </form>
    {% endif %}
    {% if ponudba.stanje == "V"  and user.uporabnik == ponudba.zakljucil%}
    <form method="post" >
        {% csrf_token %}
        {{reply_form}}
        <button class="btn btn-success" type="submit" formaction="{% url "ponudbe:transactions:finish" ponudba.id %}">Confirm</button>
        <button class="btn btn-danger" type="submit" formaction="{% url "ponudbe:transactions:cancel" ponudba.id %}">Cancel</button>
        (you can accept that you recieved the card or cancel that you didnt)
    </form>

    {% endif %}


{% endif %}

{% endblock content %}

templates/ponudbe/ponudbe.html
{% extends "index.html" %}

{% block extra_head %}

{% endblock extra_head %}

{% block title %}
my home title
{% endblock title %}


{% block content %}
<div class="container text-center">
  <div class="row p-3">
    <div class="col p-3">
      <form method="get">
        {{ filter.form.as_p }}
        <input type="submit" />
      </form>
    </div>
    <div class="border rounded p-3 col ">
      {% for obj in filter.qs %}
      <div class="position-relative">
        <a class="stretched-link"href="{% url "ponudbe:get"  obj.id%}" style="text-decoration:none"></a>
            {% include "ponudbe/ponudba.html" with ponudba=obj %}
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}