main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views


account = ([
    path('profile/', views.profile, name="profile"),
    path('user/', views.search_user, name="search"),
    path('user/<str:username>', views.get_user, name="get"),
], "accounts"
)

mod = (
    [
        path('', views.mod_home, name="homepage"),
        path('ticket/<int:ticket>', views.mod_home, name="ticket"),
        path('no_auth', views.no_auth, name="no_auth"),
        path('user/<int:user>', views.user_tickets, name="user"),
        path('comment/<int:comment_id>', views.mod_comment, name="comment"),
        path('report/<int:comment_id>', views.report, name="report"),
        path('block/<int:comment_id>', views.block, name="block"),
    ], "moderation"
)



#app_name = "main"
urlpatterns = [
    path('admin/', admin.site.urls),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("accounts/", include(account)),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", views.index, name="homepage"),
    path('ponudbe/', include("ponudbe.urls")),
    path('moderation/', include(mod)),
    path('comment/<int:parent>', views.comment, name="comment"),
]

ponudbe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

transactions = ([
    path("buy/<int:ponudba>", views.buy, name="buy"),
    path("confirm/<int:ponudba>", views.confirm, name="confirm"),
    path("recieved/<int:ponudba>", views.recieved, name="recieved"),
    path("finish/<int:ponudba>", views.finish, name="finish"),
    path("cancel/<int:ponudba>", views.cancel, name="cancel"),
    path("suggest/<int:ponudba>", views.suggest, name="suggest"),
], "transactions")

app_name = "ponudbe"
urlpatterns = [
    path("", views.index, name="index"),
    path("get/<int:ponudba_id>", views.get, name="get"),
    path("my", views.moje, name="moje"),
    path("new", views.create, name="new"),
    path("delete/<int:ponudba>", views.delete, name="delete"),
    path("edit/<int:ponudba>", views.edit, name="edit"),
    path("card-autocomplete/", views.KartaAutocomplete.as_view(), name="card_autocomplete"),
    path("transactions/", include(transactions)),
]

treasure_chest/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', include("main.urls")),
    
]
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

templates/footer.html
{% load static %}
<footer class="footer mt-auto py-3 bg-dark border-top">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md">
                Treasure Chest
            </div>
            <div class="col-12 col-md">
                <a href="{% url 'admin:index' %}">A!</a>
            </div>
        </div>
    </div>
  </footer>

templates/home.html
{% extends "index.html" %}

{% block title %}
Treasure chest OPTCG
{% endblock title %}


{% block content %}
{% if user.uporabnik %}
    welcome <code>{{user.username}}</code>
    
    <h2 class="border-bottom" data-bs-toggle="collapse" href="#suggestions" role="button" aria-expanded="false" aria-controls="suggestions">
        Cards matching your wants
    </h2>
    <div class="collapse show" id="suggestions">
        <div class="col p-3 rounded border">
            <h2 class="border-bottom" data-bs-toggle="collapse" href="#in_range" role="button" aria-expanded="false" aria-controls="in_range">
                In Range
            </h2>
            <div class="collapse show" id="in_range">
                {% for karta, sugg in range.items %}
                    {% if sugg %}
                        <h4>{{karta}}</h4>
                    {% endif %}
                    {% for ponudba in sugg %}
                        
                        <div class="position-relative">
                            <a class="stretched-link" href="{% url "ponudbe:get"  ponudba.id%}" style="text-decoration:none"></a>
                            {% include "ponudbe/ponudba.html"  with ponudba=ponudba%}
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>
        </div>
        <div class="col p-3 rounded border">
            <h2 class="border-bottom" data-bs-toggle="collapse" href="#other" role="button" aria-expanded="false" aria-controls="other">
                Other
            </h2>
            <div class="collapse show" id="other">
                {% for ponudba in trans %}
                <a href="{% url "ponudbe:get"  ponudba.id%}" style="text-decoration:none">
                    {% include "ponudbe/ponudba.html"  with ponudba=ponudba%}
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
{% endif %}

<h1>Treasure chest OPTCG:</h1>

<p>Card trading IS for One piece cards</p>
<p></p>

{% endblock content %}

templates/index.html
{% load static %}


<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    
    <title>
    {% block title %}
        ADD title
    {% endblock title %}
    </title>
    <meta name="description" content="{% block description %}add description{% endblock description %}">


    <!--BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <script
			  src="https://code.jquery.com/jquery-3.7.1.js"
			  integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
			  crossorigin="anonymous"></script>
    {% block extra_head %}
    {% endblock extra_head %}

</head>
<body class="d-flex flex-column h-100">
{% csrf_token %}
{% block nav_bar %}
{% include "nav_bar.html" %}
{% endblock nav_bar %}
<section id="content" class="container">
{% block content %}
hello world
{% endblock content %}
</section>

{% block footer %}
{% include "footer.html" %}
{% endblock footer %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/nav_bar.html
{% load static %}

<style>
    .my-navbar {
        background: var(--bs-body-bg);
    }
</style>
<header>
<nav id="nav_bar" class="sticky-top navbar navbar-expand-lg my-navbar  border-bottom">
    <div class="container">
        <a class="navbar-brand" href="{% url "homepage" %}">
            <img src="{% static 'img/chest.png' %}" alt="" style="width:64px;height:64px;">
            Treasure Chest
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle naviagtion">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="nvabbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url "homepage" %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url "accounts:search" %}">Search users</a>
              </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "ponudbe:index" %}">Ponudbe</a>
                </li>
                {% if user.uporabnik %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url "ponudbe:moje" %}">Moje Ponudbe</a>
                </li>
                {% endif %}
                {% if user.uporabnik.superuser %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url "moderation:homepage" %}">Moderation</a>
                </li>
                {% endif %}
                <li class="nav-item">
                  {% if user.is_authenticated %}
                  
                  <a class="nav-link" href="{% url "accounts:profile" %}"><i class="bi bi-person-circle"></i>{{user.username}}</a>
                  <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Log Out</button>
                  </form>
                  {% else %}
                  <a class="nav-link" href="{% url "login" %}">Log in</a>
                  <a class="nav-link" href="{% url "signup" %}">Sign up</a>
                  {% endif %}
              </li>

                <li class="nav-item py-2 py-lg-1 col-12 col-lg-auto">
                    <div class="vr d-none d-lg-flex h-100 mx-lg-2 text-white"></div>
                    <hr class="d-lg-none my-2 text-white-50">
                </li>
                <!--Dark mode button-->
                <li class="nav-item dropdown">
                    <button class="btn btn-link nav-link py-2 px-0 px-lg-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button" aria-expanded="false" data-bs-toggle="dropdown" data-bs-display="static" aria-label="Toggle theme (auto)">
                      <i class="bi bi-circle-half my-1 theme-icon-active"><use href="#circle-half"></use></i>
                      <span class="d-lg-none ms-2" id="bd-theme-text">Toggle theme</span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="bd-theme-text">
                      <li>
                        <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
                          <i class="bi bi-sun-fill me-2 opacity-50 theme-icon"><use href="#sun-fill"></use></i>
                          Light
                          <i class="bi ms-auto d-none"><use href="#check2"></use></i>
                        </button>
                      </li>
                      <li>
                        <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
                          <i class="bi bi-moon-stars-fill me-2 opacity-50 theme-icon"><use href="#moon-stars-fill"></use></i>
                          Dark
                          <i class="bi ms-auto d-none"><use href="#check2"></use></i>
                        </button>
                      </li>
                      <li>
                        <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
                          <i class="bi bi-circle-half me-2 opacity-50 theme-icon"><use href="#circle-half"></use></i>
                          Auto
                          <i class="bi ms-auto d-none"><use href="#check2"></use></i>
                        </button>
                      </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
</header>

<script async>
    (() => {
      'use strict'
    
      const getStoredTheme = () => localStorage.getItem('theme')
      const setStoredTheme = theme => localStorage.setItem('theme', theme)
    
      const getPreferredTheme = () => {
        const storedTheme = getStoredTheme()
        if (storedTheme) {
          return storedTheme
        }
    
        return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
      }
    
      const setTheme = theme => {
        if (theme === 'auto' && window.matchMedia('(prefers-color-scheme: dark)').matches) {
          document.documentElement.setAttribute('data-bs-theme', 'dark');
          document.body.classList.remove('light');
          document.body.classList.add('dark');
        } else {
          document.documentElement.setAttribute('data-bs-theme', theme);
          document.body.classList.remove('dark');
          document.body.classList.remove('light');
          document.body.classList.add(theme);

        }
      }
    
      setTheme(getPreferredTheme())
    
      const showActiveTheme = (theme, focus = false) => {
        const themeSwitcher = document.querySelector('#bd-theme')
    
        if (!themeSwitcher) {
          return
        }
    
        const themeSwitcherText = document.querySelector('#bd-theme-text')
        const activeThemeIcon = document.querySelector('.theme-icon-active use')
        const btnToActive = document.querySelector(`[data-bs-theme-value="${theme}"]`)
        const iOfActiveBtn = btnToActive.querySelector('i use').getAttribute('href')
    
        document.querySelectorAll('[data-bs-theme-value]').forEach(element => {
          element.classList.remove('active')
          element.setAttribute('aria-pressed', 'false')
        })
    
        btnToActive.classList.add('active')
        btnToActive.setAttribute('aria-pressed', 'true')
        activeThemeIcon.setAttribute('href', iOfActiveBtn)
        const themeSwitcherLabel = `${themeSwitcherText.textContent} (${btnToActive.dataset.bsThemeValue})`
        themeSwitcher.setAttribute('aria-label', themeSwitcherLabel)
    
        if (focus) {
          themeSwitcher.focus()
        }
      }
    
      window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', () => {
        const storedTheme = getStoredTheme()
        if (storedTheme !== 'light' && storedTheme !== 'dark') {
          setTheme(getPreferredTheme())
        }
      })
    
      window.addEventListener('DOMContentLoaded', () => {
        showActiveTheme(getPreferredTheme())
    
        document.querySelectorAll('[data-bs-theme-value]')
          .forEach(toggle => {
            toggle.addEventListener('click', () => {
              const theme = toggle.getAttribute('data-bs-theme-value')
              setStoredTheme(theme)
              setTheme(theme)
              showActiveTheme(theme, true)
            })
          })
      })
    })()
    </script>